title: Sadiq Shaik's Blog
author: Sadiq Shaik
email: sadiqmerajshaik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my test site

# social links
twitter_username: sadiq_shaik_7
github_username:  sadiq-shaik
show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
